Update deprecated usage of qCWarning and qCDebug
Deprecated for a while, no longer working in Qt6

Fixes compilation issues due deprecated usage:
../../../git/src/nemo-dbus/connection.cpp:255:22: error: invalid use of non-static member function 'const QLoggingCategory& NemoDBus::ConnectionData::logs()'
|   255 |         qCWarning(d->logs) << "Failed to register object on path" << path << object;

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>